// Code generated by protoc-gen-go. DO NOT EDIT.
// source: products.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Product struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price                int32    `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c6e54f42122eb82, []int{0}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Product) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Product) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

// POST
type InsertProductRequest struct {
	Product              *Product `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InsertProductRequest) Reset()         { *m = InsertProductRequest{} }
func (m *InsertProductRequest) String() string { return proto.CompactTextString(m) }
func (*InsertProductRequest) ProtoMessage()    {}
func (*InsertProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c6e54f42122eb82, []int{1}
}

func (m *InsertProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsertProductRequest.Unmarshal(m, b)
}
func (m *InsertProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsertProductRequest.Marshal(b, m, deterministic)
}
func (m *InsertProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsertProductRequest.Merge(m, src)
}
func (m *InsertProductRequest) XXX_Size() int {
	return xxx_messageInfo_InsertProductRequest.Size(m)
}
func (m *InsertProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InsertProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InsertProductRequest proto.InternalMessageInfo

func (m *InsertProductRequest) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

type InsertProductResponse struct {
	Product              *Product `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InsertProductResponse) Reset()         { *m = InsertProductResponse{} }
func (m *InsertProductResponse) String() string { return proto.CompactTextString(m) }
func (*InsertProductResponse) ProtoMessage()    {}
func (*InsertProductResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c6e54f42122eb82, []int{2}
}

func (m *InsertProductResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsertProductResponse.Unmarshal(m, b)
}
func (m *InsertProductResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsertProductResponse.Marshal(b, m, deterministic)
}
func (m *InsertProductResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsertProductResponse.Merge(m, src)
}
func (m *InsertProductResponse) XXX_Size() int {
	return xxx_messageInfo_InsertProductResponse.Size(m)
}
func (m *InsertProductResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InsertProductResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InsertProductResponse proto.InternalMessageInfo

func (m *InsertProductResponse) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

//GET
type GetProductRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProductRequest) Reset()         { *m = GetProductRequest{} }
func (m *GetProductRequest) String() string { return proto.CompactTextString(m) }
func (*GetProductRequest) ProtoMessage()    {}
func (*GetProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c6e54f42122eb82, []int{3}
}

func (m *GetProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductRequest.Unmarshal(m, b)
}
func (m *GetProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductRequest.Marshal(b, m, deterministic)
}
func (m *GetProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductRequest.Merge(m, src)
}
func (m *GetProductRequest) XXX_Size() int {
	return xxx_messageInfo_GetProductRequest.Size(m)
}
func (m *GetProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductRequest proto.InternalMessageInfo

func (m *GetProductRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetProductResponse struct {
	Product              *Product `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProductResponse) Reset()         { *m = GetProductResponse{} }
func (m *GetProductResponse) String() string { return proto.CompactTextString(m) }
func (*GetProductResponse) ProtoMessage()    {}
func (*GetProductResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c6e54f42122eb82, []int{4}
}

func (m *GetProductResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductResponse.Unmarshal(m, b)
}
func (m *GetProductResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductResponse.Marshal(b, m, deterministic)
}
func (m *GetProductResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductResponse.Merge(m, src)
}
func (m *GetProductResponse) XXX_Size() int {
	return xxx_messageInfo_GetProductResponse.Size(m)
}
func (m *GetProductResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductResponse proto.InternalMessageInfo

func (m *GetProductResponse) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

// DELETE
type DeleteProductRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteProductRequest) Reset()         { *m = DeleteProductRequest{} }
func (m *DeleteProductRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteProductRequest) ProtoMessage()    {}
func (*DeleteProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c6e54f42122eb82, []int{5}
}

func (m *DeleteProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteProductRequest.Unmarshal(m, b)
}
func (m *DeleteProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteProductRequest.Marshal(b, m, deterministic)
}
func (m *DeleteProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteProductRequest.Merge(m, src)
}
func (m *DeleteProductRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteProductRequest.Size(m)
}
func (m *DeleteProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteProductRequest proto.InternalMessageInfo

func (m *DeleteProductRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteProductResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteProductResponse) Reset()         { *m = DeleteProductResponse{} }
func (m *DeleteProductResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteProductResponse) ProtoMessage()    {}
func (*DeleteProductResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c6e54f42122eb82, []int{6}
}

func (m *DeleteProductResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteProductResponse.Unmarshal(m, b)
}
func (m *DeleteProductResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteProductResponse.Marshal(b, m, deterministic)
}
func (m *DeleteProductResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteProductResponse.Merge(m, src)
}
func (m *DeleteProductResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteProductResponse.Size(m)
}
func (m *DeleteProductResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteProductResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteProductResponse proto.InternalMessageInfo

func (m *DeleteProductResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

// UPDATE
type UpdateProductRequest struct {
	Product              *Product `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateProductRequest) Reset()         { *m = UpdateProductRequest{} }
func (m *UpdateProductRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateProductRequest) ProtoMessage()    {}
func (*UpdateProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c6e54f42122eb82, []int{7}
}

func (m *UpdateProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProductRequest.Unmarshal(m, b)
}
func (m *UpdateProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProductRequest.Marshal(b, m, deterministic)
}
func (m *UpdateProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProductRequest.Merge(m, src)
}
func (m *UpdateProductRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateProductRequest.Size(m)
}
func (m *UpdateProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProductRequest proto.InternalMessageInfo

func (m *UpdateProductRequest) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

type UpdateProductResponse struct {
	Product              *Product `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateProductResponse) Reset()         { *m = UpdateProductResponse{} }
func (m *UpdateProductResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateProductResponse) ProtoMessage()    {}
func (*UpdateProductResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c6e54f42122eb82, []int{8}
}

func (m *UpdateProductResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProductResponse.Unmarshal(m, b)
}
func (m *UpdateProductResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProductResponse.Marshal(b, m, deterministic)
}
func (m *UpdateProductResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProductResponse.Merge(m, src)
}
func (m *UpdateProductResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateProductResponse.Size(m)
}
func (m *UpdateProductResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProductResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProductResponse proto.InternalMessageInfo

func (m *UpdateProductResponse) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

// Stream
type StreamProductsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamProductsRequest) Reset()         { *m = StreamProductsRequest{} }
func (m *StreamProductsRequest) String() string { return proto.CompactTextString(m) }
func (*StreamProductsRequest) ProtoMessage()    {}
func (*StreamProductsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c6e54f42122eb82, []int{9}
}

func (m *StreamProductsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamProductsRequest.Unmarshal(m, b)
}
func (m *StreamProductsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamProductsRequest.Marshal(b, m, deterministic)
}
func (m *StreamProductsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamProductsRequest.Merge(m, src)
}
func (m *StreamProductsRequest) XXX_Size() int {
	return xxx_messageInfo_StreamProductsRequest.Size(m)
}
func (m *StreamProductsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamProductsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StreamProductsRequest proto.InternalMessageInfo

type StreamProductsResponse struct {
	Product              *Product `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamProductsResponse) Reset()         { *m = StreamProductsResponse{} }
func (m *StreamProductsResponse) String() string { return proto.CompactTextString(m) }
func (*StreamProductsResponse) ProtoMessage()    {}
func (*StreamProductsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c6e54f42122eb82, []int{10}
}

func (m *StreamProductsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamProductsResponse.Unmarshal(m, b)
}
func (m *StreamProductsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamProductsResponse.Marshal(b, m, deterministic)
}
func (m *StreamProductsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamProductsResponse.Merge(m, src)
}
func (m *StreamProductsResponse) XXX_Size() int {
	return xxx_messageInfo_StreamProductsResponse.Size(m)
}
func (m *StreamProductsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamProductsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StreamProductsResponse proto.InternalMessageInfo

func (m *StreamProductsResponse) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

func init() {
	proto.RegisterType((*Product)(nil), "products.Product")
	proto.RegisterType((*InsertProductRequest)(nil), "products.InsertProductRequest")
	proto.RegisterType((*InsertProductResponse)(nil), "products.InsertProductResponse")
	proto.RegisterType((*GetProductRequest)(nil), "products.GetProductRequest")
	proto.RegisterType((*GetProductResponse)(nil), "products.GetProductResponse")
	proto.RegisterType((*DeleteProductRequest)(nil), "products.DeleteProductRequest")
	proto.RegisterType((*DeleteProductResponse)(nil), "products.DeleteProductResponse")
	proto.RegisterType((*UpdateProductRequest)(nil), "products.UpdateProductRequest")
	proto.RegisterType((*UpdateProductResponse)(nil), "products.UpdateProductResponse")
	proto.RegisterType((*StreamProductsRequest)(nil), "products.StreamProductsRequest")
	proto.RegisterType((*StreamProductsResponse)(nil), "products.StreamProductsResponse")
}

func init() { proto.RegisterFile("products.proto", fileDescriptor_8c6e54f42122eb82) }

var fileDescriptor_8c6e54f42122eb82 = []byte{
	// 367 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x5d, 0x4b, 0xeb, 0x40,
	0x10, 0x6d, 0xfa, 0x71, 0xdb, 0x3b, 0xa5, 0x81, 0x0e, 0xed, 0xbd, 0xa1, 0x8a, 0x86, 0x15, 0xa4,
	0x20, 0x14, 0xad, 0xbf, 0x40, 0xad, 0x48, 0xdf, 0x24, 0x45, 0x04, 0xdf, 0x62, 0x32, 0x0f, 0x01,
	0x9b, 0xac, 0xbb, 0x5b, 0x7f, 0x97, 0x3f, 0x51, 0x9a, 0x8f, 0x76, 0x93, 0x6e, 0x91, 0xf6, 0x2d,
	0x3b, 0x73, 0xe6, 0xcc, 0xd9, 0x3d, 0x87, 0x80, 0xcd, 0x45, 0x12, 0xae, 0x02, 0x25, 0x27, 0x5c,
	0x24, 0x2a, 0xc1, 0x4e, 0x71, 0x66, 0x04, 0xed, 0xe7, 0xec, 0x1b, 0x6d, 0xa8, 0x47, 0xa1, 0x63,
	0xb9, 0xd6, 0xf8, 0xaf, 0x57, 0x8f, 0x42, 0x44, 0x68, 0xc6, 0xfe, 0x92, 0x9c, 0x7a, 0x5a, 0x49,
	0xbf, 0x71, 0x00, 0x2d, 0x2e, 0xa2, 0x80, 0x9c, 0x86, 0x6b, 0x8d, 0x5b, 0x5e, 0x76, 0x40, 0x17,
	0xba, 0x21, 0xc9, 0x40, 0x44, 0x5c, 0x45, 0x49, 0xec, 0x34, 0xd3, 0x01, 0xbd, 0xc4, 0x1e, 0x60,
	0x30, 0x8f, 0x25, 0x09, 0x95, 0x2f, 0xf3, 0xe8, 0x73, 0x45, 0x52, 0xe1, 0x15, 0xb4, 0x73, 0x29,
	0xe9, 0xe2, 0xee, 0xb4, 0x3f, 0xd9, 0x48, 0x2d, 0xa0, 0x05, 0x82, 0xcd, 0x60, 0x58, 0x21, 0x91,
	0x3c, 0x89, 0x25, 0x1d, 0xc6, 0x72, 0x01, 0xfd, 0x27, 0xaa, 0xea, 0xa8, 0xdc, 0x9d, 0xdd, 0x01,
	0xea, 0xa0, 0x63, 0xf6, 0x5c, 0xc2, 0x60, 0x46, 0x1f, 0xa4, 0xe8, 0x97, 0x55, 0x37, 0x30, 0xac,
	0xe0, 0xf2, 0x6d, 0x0e, 0xb4, 0xe5, 0x2a, 0x08, 0x48, 0xca, 0x14, 0xdd, 0xf1, 0x8a, 0xe3, 0xfa,
	0x35, 0x5f, 0x78, 0xe8, 0xef, 0x50, 0x1f, 0xfa, 0x9a, 0x15, 0x92, 0x63, 0x6e, 0xf9, 0x1f, 0x86,
	0x0b, 0x25, 0xc8, 0x5f, 0xe6, 0x1d, 0x99, 0x6b, 0x61, 0x8f, 0xf0, 0xaf, 0xda, 0x38, 0x82, 0x7f,
	0xfa, 0xdd, 0x00, 0x3b, 0x2f, 0x2e, 0x48, 0x7c, 0xad, 0xd3, 0xe6, 0x41, 0xaf, 0x14, 0x03, 0x3c,
	0xdb, 0xce, 0x9b, 0x42, 0x36, 0x3a, 0xdf, 0xdb, 0xcf, 0x14, 0xb1, 0x1a, 0xce, 0x01, 0xb6, 0x7e,
	0xe3, 0xc9, 0x76, 0x60, 0x27, 0x2a, 0xa3, 0x53, 0x73, 0x73, 0x43, 0xe5, 0x41, 0xaf, 0xe4, 0xa7,
	0x2e, 0xcf, 0x14, 0x08, 0x5d, 0x9e, 0x31, 0x08, 0x19, 0x67, 0xc9, 0x2b, 0x9d, 0xd3, 0x94, 0x04,
	0x9d, 0xd3, 0x68, 0x32, 0xab, 0xe1, 0x2b, 0xd8, 0x65, 0x83, 0x50, 0x1b, 0x32, 0x7a, 0x3a, 0x72,
	0xf7, 0x03, 0x0a, 0xda, 0x6b, 0xeb, 0xbe, 0xf5, 0xd6, 0xf0, 0x79, 0xf4, 0xfe, 0x27, 0xfd, 0xd5,
	0xdc, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0xd9, 0xcf, 0xc4, 0x5f, 0x7c, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProductServiceClient is the client API for ProductService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProductServiceClient interface {
	InsertProduct(ctx context.Context, in *InsertProductRequest, opts ...grpc.CallOption) (*InsertProductResponse, error)
	GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*GetProductResponse, error)
	DeleteProduct(ctx context.Context, in *DeleteProductRequest, opts ...grpc.CallOption) (*DeleteProductResponse, error)
	UpdateProduct(ctx context.Context, in *UpdateProductRequest, opts ...grpc.CallOption) (*UpdateProductResponse, error)
	StreamProducts(ctx context.Context, in *StreamProductsRequest, opts ...grpc.CallOption) (ProductService_StreamProductsClient, error)
}

type productServiceClient struct {
	cc *grpc.ClientConn
}

func NewProductServiceClient(cc *grpc.ClientConn) ProductServiceClient {
	return &productServiceClient{cc}
}

func (c *productServiceClient) InsertProduct(ctx context.Context, in *InsertProductRequest, opts ...grpc.CallOption) (*InsertProductResponse, error) {
	out := new(InsertProductResponse)
	err := c.cc.Invoke(ctx, "/products.ProductService/InsertProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*GetProductResponse, error) {
	out := new(GetProductResponse)
	err := c.cc.Invoke(ctx, "/products.ProductService/GetProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) DeleteProduct(ctx context.Context, in *DeleteProductRequest, opts ...grpc.CallOption) (*DeleteProductResponse, error) {
	out := new(DeleteProductResponse)
	err := c.cc.Invoke(ctx, "/products.ProductService/DeleteProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) UpdateProduct(ctx context.Context, in *UpdateProductRequest, opts ...grpc.CallOption) (*UpdateProductResponse, error) {
	out := new(UpdateProductResponse)
	err := c.cc.Invoke(ctx, "/products.ProductService/UpdateProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) StreamProducts(ctx context.Context, in *StreamProductsRequest, opts ...grpc.CallOption) (ProductService_StreamProductsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ProductService_serviceDesc.Streams[0], "/products.ProductService/StreamProducts", opts...)
	if err != nil {
		return nil, err
	}
	x := &productServiceStreamProductsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ProductService_StreamProductsClient interface {
	Recv() (*StreamProductsResponse, error)
	grpc.ClientStream
}

type productServiceStreamProductsClient struct {
	grpc.ClientStream
}

func (x *productServiceStreamProductsClient) Recv() (*StreamProductsResponse, error) {
	m := new(StreamProductsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ProductServiceServer is the server API for ProductService service.
type ProductServiceServer interface {
	InsertProduct(context.Context, *InsertProductRequest) (*InsertProductResponse, error)
	GetProduct(context.Context, *GetProductRequest) (*GetProductResponse, error)
	DeleteProduct(context.Context, *DeleteProductRequest) (*DeleteProductResponse, error)
	UpdateProduct(context.Context, *UpdateProductRequest) (*UpdateProductResponse, error)
	StreamProducts(*StreamProductsRequest, ProductService_StreamProductsServer) error
}

// UnimplementedProductServiceServer can be embedded to have forward compatible implementations.
type UnimplementedProductServiceServer struct {
}

func (*UnimplementedProductServiceServer) InsertProduct(ctx context.Context, req *InsertProductRequest) (*InsertProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InsertProduct not implemented")
}
func (*UnimplementedProductServiceServer) GetProduct(ctx context.Context, req *GetProductRequest) (*GetProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProduct not implemented")
}
func (*UnimplementedProductServiceServer) DeleteProduct(ctx context.Context, req *DeleteProductRequest) (*DeleteProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProduct not implemented")
}
func (*UnimplementedProductServiceServer) UpdateProduct(ctx context.Context, req *UpdateProductRequest) (*UpdateProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProduct not implemented")
}
func (*UnimplementedProductServiceServer) StreamProducts(req *StreamProductsRequest, srv ProductService_StreamProductsServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamProducts not implemented")
}

func RegisterProductServiceServer(s *grpc.Server, srv ProductServiceServer) {
	s.RegisterService(&_ProductService_serviceDesc, srv)
}

func _ProductService_InsertProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).InsertProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/products.ProductService/InsertProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).InsertProduct(ctx, req.(*InsertProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/products.ProductService/GetProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetProduct(ctx, req.(*GetProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_DeleteProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).DeleteProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/products.ProductService/DeleteProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).DeleteProduct(ctx, req.(*DeleteProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_UpdateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).UpdateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/products.ProductService/UpdateProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).UpdateProduct(ctx, req.(*UpdateProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_StreamProducts_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamProductsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProductServiceServer).StreamProducts(m, &productServiceStreamProductsServer{stream})
}

type ProductService_StreamProductsServer interface {
	Send(*StreamProductsResponse) error
	grpc.ServerStream
}

type productServiceStreamProductsServer struct {
	grpc.ServerStream
}

func (x *productServiceStreamProductsServer) Send(m *StreamProductsResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _ProductService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "products.ProductService",
	HandlerType: (*ProductServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InsertProduct",
			Handler:    _ProductService_InsertProduct_Handler,
		},
		{
			MethodName: "GetProduct",
			Handler:    _ProductService_GetProduct_Handler,
		},
		{
			MethodName: "DeleteProduct",
			Handler:    _ProductService_DeleteProduct_Handler,
		},
		{
			MethodName: "UpdateProduct",
			Handler:    _ProductService_UpdateProduct_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamProducts",
			Handler:       _ProductService_StreamProducts_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "products.proto",
}
